/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// i have now runned this program practically just written it for practice , because i don't have the microcontroller at this moment.
#include <stdint.h>
#include <stdio.h>
#include "math.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	printf("The sum is %d \n",math_add(0x0fff1111,0x0fff1111));

	printf("The product is %64llx \n",math_mul(0x0fff1111,0x0ffff1111));

	printf("The division is %f \n",math_div(100,8));


    return 0;
}
